# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12
      - name: Maven Package
        run: mvn -B clean package --file pom.xml
      - name: Maven Verify
        run: mvn -B clean verify install
  
  artifact:
      name: Artifact
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: Set up JDK 12
          uses: actions/setup-java@v1
          with:
            java-version: 12
        - name: Maven clean install
          run: mvn -B clean install deploy --file pom.xml
